### ISSUE TITLE
转换失败 org.json.JSONException: Expected a ':' after a key 

### ISSUE THREAD

**Issue by DRPrincess** [zzz40500/GsonFormat#110]
测试数据
```
{
        "type":"测试",
        "value":"测试",
        "displayName":"测试",
        "seq":4
 }
```
出现问题：
```
org.json.JSONException: Expected a ':' after a key at 11 [character 9 line 2]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:208)
	at org.json.JSONObject.<init>(JSONObject.java:317)
	at org.gsonformat.intellij.ConvertBridge.parseJSONObject(ConvertBridge.java:133)
	at org.gsonformat.intellij.ConvertBridge.run(ConvertBridge.java:103)
	at org.gsonformat.intellij.ui.JsonDialog.onOK(JsonDialog.java:190)
	at org.gsonformat.intellij.ui.JsonDialog.access$200(JsonDialog.java:19)
	at org.gsonformat.intellij.ui.JsonDialog$1.actionPerformed(JsonDialog.java:57)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```
问题分析：

已经排除格式错误，那么导致这个问题的很有可能就是编码的问题。而且当我发布完这个 issue  后，我复制 issue 中我贴的 json 解析是没问题的，估计是因为 GitHub 转换了编码的原因。
为了确认这个问题，我用UltraEdit 以 HEX 模式分别打开了两个相同内容的文件，发现果然不一样。

正常转换的文本：

![image](https://user-images.githubusercontent.com/16207639/33135900-665be874-cf69-11e7-9e4a-29991f0ff107.png)

转换失败的文本：

![image](https://user-images.githubusercontent.com/16207639/33136041-cc643590-cf69-11e7-8aeb-ec6fde8da68a.png)

分析到这里，已经确认了编码的原因，但是从hex模式才能看出来，正常从文本内容上看，是没有区别的。遇到这种编码的问题不知道怎么修改，才能正常使用。

后续更改：

通过UltraEdit 以 HEX 模式，发现多了 `Â` 这个字符，仔细看的话，无法转换的文本中，是所有空格转换成了这个字符，于是定位到空格上面，发现两个的区别就在于，一个是全角空格，一个是半角空格。全角空格无法正常转换。

因为我们的接口是word文档给的，于是，我全局替换了全角空格为半角空格，就好了。

**Comment by DRPrincess** [comment]
就这么提了一个乌龙的 issue ..... 😂
