### ISSUE TITLE
v1.5 在idea 2018.2.4 不能用

### ISSUE THREAD

**Issue by zm9913** [zzz40500/GsonFormat#127]
idea 2018.2.4 
java.lang.NullPointerException
	at org.gsonformat.intellij.ConvertBridge.removeComment(ConvertBridge.java:248)
	at org.gsonformat.intellij.ConvertBridge.collectDeclareFields(ConvertBridge.java:262)
	at org.gsonformat.intellij.ConvertBridge.collectClassAttribute(ConvertBridge.java:200)
	at org.gsonformat.intellij.ConvertBridge.handleClassReferenceType(ConvertBridge.java:377)
	at org.gsonformat.intellij.ConvertBridge.evalFieldEntity(ConvertBridge.java:343)
	at org.gsonformat.intellij.ConvertBridge.collectDeclareFields(ConvertBridge.java:284)
	at org.gsonformat.intellij.ConvertBridge.collectClassAttribute(ConvertBridge.java:200)
	at org.gsonformat.intellij.ConvertBridge.run(ConvertBridge.java:110)

**Comment by FoghostCn** [comment]
+1
