### ISSUE TITLE
不能解析

### ISSUE THREAD

**Issue by SharerMax** [zzz40500/GsonFormat#26]
2015-10-18 17:54:59,333 [1949939]  ERROR - er.FormattingDocumentModelImpl - Document and psi file texts should be equal: PsiJavaFile:BookReview.java file length = 1132, document length = 757 
	com.intellij.openapi.diagnostic.Logger$EmptyThrowable
		at com.intellij.openapi.diagnostic.Logger.error(Logger.java:117)
		at com.intellij.psi.formatter.FormattingDocumentModelImpl.createOn(FormattingDocumentModelImpl.java:68)
		at com.intellij.lang.java.JavaFormattingModelBuilder.createModel(JavaFormattingModelBuilder.java:58)
		at com.intellij.formatting.CoreFormatterUtil.buildModel(CoreFormatterUtil.java:48)
		at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processText(CodeFormatterFacade.java:230)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$ReformatRangesAction.execute(PostprocessReformattingAspect.java:745)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormattingInner(PostprocessReformattingAspect.java:357)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.access$1200(PostprocessReformattingAspect.java:62)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$8$1.run(PostprocessReformattingAspect.java:261)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:112)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:109)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$8.run(PostprocessReformattingAspect.java:258)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:180)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.atomic(PostprocessReformattingAspect.java:174)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponedFormattingImpl(PostprocessReformattingAspect.java:252)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormatting(PostprocessReformattingAspect.java:248)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$7.run(PostprocessReformattingAspect.java:230)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:180)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.atomic(PostprocessReformattingAspect.java:174)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormatting(PostprocessReformattingAspect.java:223)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.decrementPostponedCounter(PostprocessReformattingAspect.java:160)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.access$300(PostprocessReformattingAspect.java:62)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$2.writeActionFinished(PostprocessReformattingAspect.java:100)
		at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
		at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
		at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
		at com.sun.proxy.$Proxy2.writeActionFinished(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.fireWriteActionFinished(ApplicationImpl.java:1351)
		at com.intellij.openapi.application.impl.ApplicationImpl.endWrite(ApplicationImpl.java:1197)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
		at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
		at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
		at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
		at FieldsDialog.onOK(FieldsDialog.java:142)
		at FieldsDialog.access$000(FieldsDialog.java:27)
		at FieldsDialog$2.actionPerformed(FieldsDialog.java:89)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
		at java.awt.Component.processMouseEvent(Component.java:6535)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
		at java.awt.Component.processEvent(Component.java:6300)
		at java.awt.Container.processEvent(Container.java:2236)
		at java.awt.Component.dispatchEventImpl(Component.java:4891)
		at java.awt.Container.dispatchEventImpl(Container.java:2294)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
		at java.awt.Container.dispatchEventImpl(Container.java:2280)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	2015-10-18 17:54:59,334 [1949940]  ERROR - er.FormattingDocumentModelImpl - Android Studio 1.4  Build #AI-141.2288178 
	2015-10-18 17:54:59,334 [1949940]  ERROR - er.FormattingDocumentModelImpl - JDK: 1.8.0_60 
	2015-10-18 17:54:59,334 [1949940]  ERROR - er.FormattingDocumentModelImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
	2015-10-18 17:54:59,334 [1949940]  ERROR - er.FormattingDocumentModelImpl - Vendor: Oracle Corporation 
	2015-10-18 17:54:59,334 [1949940]  ERROR - er.FormattingDocumentModelImpl - OS: Windows 10 
	2015-10-18 17:54:59,335 [1949941]  ERROR - er.FormattingDocumentModelImpl - Last Action: Generate 
	2015-10-18 17:54:59,335 [1949941]  ERROR - er.FormattingDocumentModelImpl - Current Command: Undefined 
	2015-10-18 17:54:59,335 [1949941]  ERROR - ellij.formatting.FormatterImpl - Document length 757 doesn't match PSI file length 1132, language: Language: JAVA 
	com.intellij.formatting.FormatterImpl$FormattingModelInconsistencyException: Document length 757 doesn't match PSI file length 1132, language: Language: JAVA
		at com.intellij.formatting.FormatterImpl.validateModel(FormatterImpl.java:946)
		at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:246)
		at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processText(CodeFormatterFacade.java:243)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$ReformatRangesAction.execute(PostprocessReformattingAspect.java:745)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormattingInner(PostprocessReformattingAspect.java:357)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.access$1200(PostprocessReformattingAspect.java:62)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$8$1.run(PostprocessReformattingAspect.java:261)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:112)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:109)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$8.run(PostprocessReformattingAspect.java:258)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:180)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.atomic(PostprocessReformattingAspect.java:174)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.postponedFormattingImpl(PostprocessReformattingAspect.java:252)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormatting(PostprocessReformattingAspect.java:248)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$7.run(PostprocessReformattingAspect.java:230)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:180)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.atomic(PostprocessReformattingAspect.java:174)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.doPostponedFormatting(PostprocessReformattingAspect.java:223)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.decrementPostponedCounter(PostprocessReformattingAspect.java:160)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect.access$300(PostprocessReformattingAspect.java:62)
		at com.intellij.psi.impl.source.PostprocessReformattingAspect$2.writeActionFinished(PostprocessReformattingAspect.java:100)
		at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
		at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
		at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
		at com.sun.proxy.$Proxy2.writeActionFinished(Unknown Source)
		at com.intellij.openapi.application.impl.ApplicationImpl.fireWriteActionFinished(ApplicationImpl.java:1351)
		at com.intellij.openapi.application.impl.ApplicationImpl.endWrite(ApplicationImpl.java:1197)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
		at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
		at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
		at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
		at FieldsDialog.onOK(FieldsDialog.java:142)
		at FieldsDialog.access$000(FieldsDialog.java:27)
		at FieldsDialog$2.actionPerformed(FieldsDialog.java:89)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
		at java.awt.Component.processMouseEvent(Component.java:6535)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
		at java.awt.Component.processEvent(Component.java:6300)
		at java.awt.Container.processEvent(Container.java:2236)
		at java.awt.Component.dispatchEventImpl(Component.java:4891)
		at java.awt.Container.dispatchEventImpl(Container.java:2294)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
		at java.awt.Container.dispatchEventImpl(Container.java:2280)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	2015-10-18 17:54:59,336 [1949942]  ERROR - ellij.formatting.FormatterImpl - Android Studio 1.4  Build #AI-141.2288178 
	2015-10-18 17:54:59,336 [1949942]  ERROR - ellij.formatting.FormatterImpl - JDK: 1.8.0_60 
	2015-10-18 17:54:59,336 [1949942]  ERROR - ellij.formatting.FormatterImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
	2015-10-18 17:54:59,336 [1949942]  ERROR - ellij.formatting.FormatterImpl - Vendor: Oracle Corporation 
	2015-10-18 17:54:59,336 [1949942]  ERROR - ellij.formatting.FormatterImpl - OS: Windows 10 
	2015-10-18 17:54:59,337 [1949943]  ERROR - ellij.formatting.FormatterImpl - Last Action: Generate 
	2015-10-18 17:54:59,337 [1949943]  ERROR - ellij.formatting.FormatterImpl - Current Command: Undefined 
	2015-10-18 17:54:59,337 [1949943]  ERROR - llij.ide.plugins.PluginManager - Wrong line separators: '...d.cn/?p=67\r\n\r\n\r\nÄÇÌìÎÒµÚ...' at offset 245 
	java.lang.AssertionError: Wrong line separators: '...d.cn/?p=67\r\n\r\n\r\nÄÇÌìÎÒµÚ...' at offset 245
		at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:66)
		at com.intellij.openapi.diagnostic.Logger.error(Logger.java:117)
		at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2518)
		at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:635)
		at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:492)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer.doCommitTransaction(PsiToDocumentSynchronizer.java:287)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:262)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:102)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:126)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer.doSync(PsiToDocumentSynchronizer.java:99)
		at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:259)
		at com.intellij.pom.core.impl.PomModelImpl.commitTransaction(PomModelImpl.java:235)
		at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:194)
		at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:165)
		at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:658)
		at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:765)
		at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:81)
		at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:544)
		at com.intellij.psi.impl.source.tree.java.ClassElement.addInternal(ClassElement.java:169)
		at com.intellij.psi.impl.source.JavaStubPsiElement.add(JavaStubPsiElement.java:79)
		at entity.FieldEntity.generateFiled(FieldEntity.java:158)
		at entity.InnerClassEntity.generateFiled(InnerClassEntity.java:140)
		at WriterUtil.run(WriterUtil.java:38)
		at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:166)
		at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
		at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
		at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
		at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
		at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
		at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
		at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
		at FieldsDialog.onOK(FieldsDialog.java:142)
		at FieldsDialog.access$000(FieldsDialog.java:27)
		at FieldsDialog$2.actionPerformed(FieldsDialog.java:89)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
		at java.awt.Component.processMouseEvent(Component.java:6535)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
		at java.awt.Component.processEvent(Component.java:6300)
		at java.awt.Container.processEvent(Container.java:2236)
		at java.awt.Component.dispatchEventImpl(Component.java:4891)
		at java.awt.Container.dispatchEventImpl(Container.java:2294)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
		at java.awt.Container.dispatchEventImpl(Container.java:2280)
		at java.awt.Window.dispatchEventImpl(Window.java:2750)
		at java.awt.Component.dispatchEvent(Component.java:4713)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
		at java.awt.EventQueue$4.run(EventQueue.java:731)
		at java.awt.EventQueue$4.run(EventQueue.java:729)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	Caused by: com.intellij.openapi.diagnostic.Logger$EmptyThrowable
		... 74 more
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - Android Studio 1.4  Build #AI-141.2288178 
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_60 
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
	2015-10-18 17:54:59,338 [1949944]  ERROR - llij.ide.plugins.PluginManager - Last Action: Generate

**Comment by SharerMax** [comment]
附上解析串：  

    {
        "id":1000104,
        "title":"长大就笨了",
        "alt":"http:\/\/book.douban.com\/review\/1000104\/",
        "author":User,
        "book":Book,
        "rating":{
            "max":5,
            "value":"5",
            "min":1
            },
        "votes":1376,
        "useless":36,
        "comments":292,
        "summary":"「我在」：http://www.bighead.cn/?p=67\r\n\r\n\r\n那天我第一次打开《小王子》，就呆了。不是因为它的清新剔透，而是圣...",
        "published":"2005-04-06 11:51:52",
        "updated":"2012-08-30 20:48:23"
    }

重现步骤：  
1. 先实现空的Parcelable接口
2. 再用GsonFormat生成

**Comment by SharerMax** [comment]
直接生成也不可以

**Comment by zzz40500** [comment]
我查查..

**Comment by zzz40500** [comment]
json 中出现的 \r\n\r\n\r\n 导致的.最近会发个修复包出来.

**Comment by SharerMax** [comment]
nice

**Comment by zzz40500** [comment]
新版本已经修复，你更新试试看

**Comment by SharerMax** [comment]
已修复
