### ISSUE TITLE
json数据生成实体类报错

### ISSUE THREAD

**Issue by dan907779114** [zzz40500/GsonFormat#50]
[
    {
        "id": "c41651a5b8a843b4b28cad204b3083a8",
        "title": "南京市职工职业(行业)技能大赛正式启动",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603104509422683501.png",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=c41651a5b8a843b4b28cad204b3083a8",
        "reportTime": 1464921909000,
        "time": "2016-06-03 "
    },
    {
        "id": "cbd5ab4362c844798e46fc50de0d6416",
        "title": "质检总局：激光笔隐患最大 可致永久伤害",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/22041431560097984.jpg",
        "isShow": 1,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=cbd5ab4362c844798e46fc50de0d6416",
        "reportTime": 1464922783000,
        "time": "2016-06-03 "
    },
    {
        "id": "8bffe6a965644eb6850105c5f3c0b114",
        "title": "江苏省第五次青年作家创作会议在南京开幕",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160612173312251182689.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=8bffe6a965644eb6850105c5f3c0b114",
        "reportTime": 1465179320000,
        "time": "2016-06-06 "
    },
    {
        "id": "af1bc195288642a18244035b5aea9287",
        "title": "2016年全国五一劳动奖表彰大会在京举行",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/2016060311083339828108.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=af1bc195288642a18244035b5aea9287",
        "reportTime": 1464923313000,
        "time": "2016-06-03 "
    },
    {
        "id": "28e395a9d8434ae5823cab33a9839fd2",
        "title": "全国总工会机关举办\u201c两学一做\u201d学习教育 党务干部专题培训班",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603111547919600794.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=28e395a9d8434ae5823cab33a9839fd2",
        "reportTime": 1464923747000,
        "time": "2016-06-03 "
    },
    {
        "id": "b2856d392c88423187826186ab773cea",
        "title": "全总十六届经审会第六次全体会议召开",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603124441213472677.png",
        "isShow": 1,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=b2856d392c88423187826186ab773cea",
        "reportTime": 1464929081000,
        "time": "2016-06-03 "
    },
    {
        "id": "8ad3bb0c14fa4ca4b8c654bf74d1a219",
        "title": "省总机关团委开展青年拓展活动",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603130324382678030.png",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=8ad3bb0c14fa4ca4b8c654bf74d1a219",
        "reportTime": 1464930204000,
        "time": "2016-06-03 "
    },
    {
        "id": "fee4a8c502a7459e99463e159664c5ad",
        "title": "市总采取系列措施加强工资集体协商指导员队伍建设  ",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603130724163207967.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=fee4a8c502a7459e99463e159664c5ad",
        "reportTime": 1464930444000,
        "time": "2016-06-03 "
    },
    {
        "id": "3b4298eb021747649896ad9d6ed65795",
        "title": "全市街道（镇）总工会成立观摩推进会在玄武区锁金村街道总工会召开",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603130843812303585.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=3b4298eb021747649896ad9d6ed65795",
        "reportTime": 1464930523000,
        "time": "2016-06-03 "
    },
    {
        "id": "be8d6f94a99c45518e9b3564c408aac1",
        "title": "南汽举办第四届职工登山比赛",
        "thumbnail": "http://49.65.2.70/vp-standweb/fileUpload/info/20160603131958306121064.jpg",
        "isShow": 0,
        "flag": 1,
        "imgUrl": null,
        "videoAddress": null,
        "fileAddress": null,
        "detailUrl": "http://49.65.2.70/vp-member/sys/info/detailInfo?id=be8d6f94a99c45518e9b3564c408aac1",
        "reportTime": 1464931198000,
        "time": "2016-06-03 "
    }
]

报的错：
org.json.JSONException: Expected a ',' or '}' at 129 [character 37 line 4]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
    at org.json.JSONObject.<init>(JSONObject.java:225)
    at org.json.JSONObject.<init>(JSONObject.java:317)
    at ConvertBridge.run(ConvertBridge.java:103)
    at JsonUtilsDialog.onOK(JsonUtilsDialog.java:195)
    at JsonUtilsDialog.access$200(JsonUtilsDialog.java:19)
    at JsonUtilsDialog$1.actionPerformed(JsonUtilsDialog.java:61)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:729)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:688)
    at java.awt.EventQueue$3.run(EventQueue.java:686)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:702)
    at java.awt.EventQueue$4.run(EventQueue.java:700)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by xmliu** [comment]
[https://github.com/zzz40500/GsonFormat/issues/49](url)就像作者说的，像这种数组类的，解析一个item就行，不然你就带大括号一起解析

**Comment by zzz40500** [comment]
升级到1.3.0 已支持这样的解析
