### ISSUE TITLE
path err OPL

### ISSUE THREAD

**Issue by hellyeahhhhhhh** [zzz40500/GsonFormat#51]
转换为fastjson的时候报错，错误信息：
org.json.JSONException: JSONArray[0] not found.
	at org.json.JSONArray.get(JSONArray.java:194)
	at ConvertBridge.handJSONArray(ConvertBridge.java:561)
	at ConvertBridge.typeByValue(ConvertBridge.java:456)
	at ConvertBridge.createFiled(ConvertBridge.java:416)
	at ConvertBridge.createFields(ConvertBridge.java:386)
	at ConvertBridge.parseJson(ConvertBridge.java:298)
	at ConvertBridge.run(ConvertBridge.java:124)
	at JsonUtilsDialog.onOK(JsonUtilsDialog.java:188)
	at JsonUtilsDialog.access$200(JsonUtilsDialog.java:16)
	at JsonUtilsDialog$1.actionPerformed(JsonUtilsDialog.java:60)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

数据如下：
{
    "list": [
        {
            "an_title": "标志着国民党由片面抗战逐步转为消极抗战的会议是",
            "solution_select": "国民党五全大会==国民党五届五中全会==国民党六届二中全会==国民党六全大会 ",
            "correct_select": "B"
        },
        {
            "an_title": "新中国第一次正式提出实现“四个现代化”奋斗目标的会议是",
            "solution_select": "第一届全国人民代表大会==第二届全国人民代表大会==第三届全国人民代表大会 ==第四届全国人民代表大会",
            "correct_select": "C"
        },
        {
            "an_title": "1962年初，中共中央召开的扩大的中央工作会议是",
            "solution_select": "“七千人大会”==庐山会议==南宁会议==武昌会议",
            "correct_select": "A"
        },
        {
            "an_title": "新文化运动的基本口号是",
            "solution_select": "科学、进步==独立、富强==民主、科学==自由、民主 ",
            "correct_select": "C"
        },
        {
            "an_title": "1860年洗劫和烧毁圆明园的外国侵略军是",
            "solution_select": "日本侵略军==英法联军==俄国侵略军==八国联军",
            "correct_select": "B"
        },
        {
            "an_title": "规定中国割让九龙半岛南端和昂船洲，“归英属香港界内”的条约是",
            "solution_select": "《南京条约》==《天津条约》==《辛丑条约》==《北京条约》",
            "correct_select": "D"
        },
        {
            "an_title": "抗日民族统一战线中的顽固势力是指",
            "solution_select": "民族资产阶级==城市小资产阶级==大地主大资产阶级的抗日派==地方实力派",
            "correct_select": "C"
        },
        {
            "an_title": "1948年11月至1949年1月，担任淮海战役总前委书记的是",
            "solution_select": "邓小平==刘伯承==陈毅==粟裕",
            "correct_select": "A"
        },
        {
            "an_title": "1951年底到1952年春，中国共产党在党政机构工作人员中开",
            "solution_select": "肃反运动==整风、整党运动==“三反”运动==“五反”运动",
            "correct_select": "C"
        },
        {
            "an_title": "引发五四运动的直接导火线是",
            "solution_select": "袁世凯复辟帝制==中共“三大”的召开==五卅惨案==巴黎和会上中国外交的失败 ",
            "correct_select": "D"
        },
        {
            "an_title": "1935年1月，在长征途中召开的中共中央政治局扩大会议是",
            "solution_select": "古田会议==遵义会议==瓦窑堡会议==洛川会议",
            "correct_select": "B"
        },
        {
            "an_title": "新中国成立初期，指导新解放区农村土地改革运动的文件是",
            "solution_select": "《中国土地法大纲》==《中国人民政治协商会议共同纲领》==《中华人民共和国土地改革法》==《中华人民共和国宪法》 ",
            "correct_select": "C"
        },
        {
            "an_title": "中国历史上第一部具有资产阶级共和国宪法性质的法典是",
            "solution_select": "《中华民国临时约法》==《中华民国约法》==《钦定宪法大纲》==《中华民国宪法》",
            "correct_select": "A"
        },
        {
            "an_title": "1911年4月，资产阶级革命派在黄兴带领下举行的起义是",
            "solution_select": "惠州起义==河口起义==广州起义==武昌起义",
            "correct_select": "C"
        },
        {
            "an_title": "1930年6月至1930年9月，中国共产党内出现的主要错误倾",
            "solution_select": "“左”倾盲动主义==“左”倾教条主义==“左”倾冒险主义==“右”倾机会主义 ",
            "correct_select": "C"
        },
        {
            "an_title": "中国共产党开展的延安整风运动最主要的任务是",
            "solution_select": "反对主观主义==反对宗派主义==反对官僚主义==反对党八股",
            "correct_select": "A"
        },
        {
            "an_title": "天京事变后，率部出走的太平天国领导成员是",
            "solution_select": "李秀成==石达开==杨秀清==韦昌辉",
            "correct_select": "B"
        },
        {
            "an_title": "中共十四大明确提出，我国经济体制改革的目标是建立",
            "solution_select": "社会主义有计划商品经济体制==社会主义市场经济体制==计划为主、市场为辅的经济体制==市场为主、计划为辅的经济体制",
            "correct_select": "B"
        },
        {
            "an_title": "1931年，日本帝国主义制造的侵略中国东北的事变是",
            "solution_select": "九一八事变==一·二八事变==七七事变==八一三事变",
            "correct_select": "A"
        },
        {
            "an_title": "1895年，日本迫使清朝政府签订的不平等条约是",
            "solution_select": "《南京条约》==《天津条约》==《马关条约》==《辛丑条约》",
            "correct_select": "C"
        }
    ],
    "list1": [
        {
            "an_title": "甲午战争前西方列强迫使中国政府签订的不平等条约有",
            "solution_select": "《南京条约》==《中法新约》==《辛丑条约》==《马关条约》",
            "correct_select": "A,B"
        },
        {
            "an_title": "在国民党统治时期，四大家族垄断的大银行有",
            "solution_select": "中央银行==中国银行==交通银行==中国农民银行",
            "correct_select": "A,B,C,D"
        },
        {
            "an_title": "中共七届二中全会的主要内容有",
            "solution_select": "阐明了人民民主专政理论==规定了全国胜利后中国共产党在政治、经济、外交方面应当采取的基本政策==指出了中国由农业国转变为工业国、由新民主主义社会转变为社会主义社会的发展方向==在中国共产党自身建设问题上，提出了“两个务必”的要求",
            "correct_select": "B,C,D"
        },
        {
            "an_title": "洋务派兴办民用企业的主要方式有",
            "solution_select": "官督商办==官商合办==商办==官办 ",
            "correct_select": "A,B,D"
        },
        {
            "an_title": "新文化运动的主要内容有",
            "solution_select": "主张社会革命==提倡民主和科学==主张文学革命==提倡白话文和新文学",
            "correct_select": "B,C,D"
        },
        {
            "an_title": "洋务运动失败的原因是",
            "solution_select": "洋务运动具有封建性==洋务运动对西方列强具有依赖性==洋务企业管理具有腐朽性==顽固势力多方阻挠",
            "correct_select": "A,B,C,D"
        },
        {
            "an_title": "1967年，在所谓“二月逆流”中与中央文革小组错误做法进行抗",
            "solution_select": "谭震林==陈毅==叶剑英==李富春",
            "correct_select": "A,B,C,D"
        },
        {
            "an_title": "1933年11月，发动抗日反蒋的福建事变的国民党十九路军将领",
            "solution_select": "冯玉祥==蔡廷锴==吉鸿昌==蒋光鼐",
            "correct_select": "B,D"
        },
        {
            "an_title": "周恩来总理在第三届全国人民代表大会第一次会议上正式宣布，我国",
            "solution_select": "工业现代化==农业现代化==国防现代化==科学技术现代化",
            "correct_select": "A,B,C,D"
        },
        {
            "an_title": "在中国抗战的战略防御阶段，国民党组织的大战役有",
            "solution_select": "武汉会战==第三次长沙会战==淞沪会战==桂南会战 ",
            "correct_select": "A,C"
        }
    ],
    "list2": [],
    "list3": [],
    "list4": [
        {
            "an_title": "新民主主义革命总路线及新民主主义革命的三大经济纲领是什么?",
            "explain_solution": "1、新民主主义革命总路线：\n 无产阶级领导的，人民大众的，反对帝国主义、封建主义和官僚资本主义的革命。\n2.、新民主主义革命的三大经济纲领：\n（1）没收封建阶级的土地归农民所有 ；\n　　 （2）没收蒋介石、宋子文、孔祥熙、陈立夫为首的垄断资本归新民主主义的国家所有； \n（3）保护民族工商业。"
        },
        {
            "an_title": "旧民主主义革命时期中国人民反侵略斗争失败的主要原因是什么?",
            "explain_solution": "（1）社会制度的腐败。近代以来封建社会制度没有根本改变。清政府为了维护自己的统治，经常压制人民的反抗斗争，力主避战求和，为此不惜割地、赔款。\n（2）经济技术的落后。近代以来，中国经济技术落后，导致中国在武器装备、军队素质、综合实力等方面远远落后于帝国主义列强，必然导致被动挨打。\n经济技术的落后是中国反侵略战争失败的重要原因，但根本原因还是社会制度的腐败。"
        },
        {
            "an_title": "资产阶级革命派与改良派论战的主要问题是什么?",
            "explain_solution": "1要不要以革命手段推翻清政府 2要不要推翻帝制,实行共和 3要不要进行社会革命"
        },
        {
            "an_title": "我国社会主义改造基本完成的意义是什么?",
            "explain_solution": "第一社会主义制度的建立是我国历史上最深刻最伟大的社会变革是中华人民共和国发展中的一个重要里程碑。第二中国社会主义改造创造了一系列从低级到高级的逐步过渡的形式用和平的方法改造个体农业、手工业和资本主义工商业在历史上第一次实现了马克思和列宁关于对资产阶级和平赎买的设想。我国社会主义改造胜利完成的事实表明社会主义的基本经济制度已经在我国建立起来中国已经从新民主主义社会进入到社会主义社会的初级阶段。它为进一步发展我国的社会生产力使全国人民逐步过上富裕的生活为中国今后的发展和进步奠定了重要的基础。"
        },
        {
            "an_title": "解放战争时期的土地改革运动使解放区出现了哪些新面貌？",
            "explain_solution": "经过土地改革运动，解放区出现的新面貌主要是：\n（1）广大农民对中国共产党更加信任和拥护，工农联盟以及解放区的人民民主政权得到进一步巩固和加强。\n（2）广大农民从封建的生产关系中解放出来，生产积极性空前提高，解放区农村的经济面貌得到明显改观。 \n（3）大批青壮年农民踊跃参军，配合解放军作战，人民解放战争有了巩固的后方和最基本的人力和物力保证。"
        }
    ]
}

**Comment by hellyeahhhhhhh** [comment]
更新了插件就好了，也是被自己蠢哭。。。
