### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ACEMerlin** [zzz40500/GsonFormat#63]
null
java.lang.StackOverflowError
	at com.intellij.util.containers.ConcurrentHashMap.computeHashCode(ConcurrentHashMap.java:3593)
	at com.intellij.util.containers.ConcurrentHashMap.hash(ConcurrentHashMap.java:3602)
	at com.intellij.util.containers.ConcurrentHashMap.get(ConcurrentHashMap.java:945)
	at com.intellij.util.pico.DefaultPicoContainer.getFromCache(DefaultPicoContainer.java:83)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at com.intellij.psi.impl.source.resolve.ResolveCache.getInstance(ResolveCache.java:46)
	at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.multiResolve(ClsJavaCodeReferenceElementImpl.java:192)
	at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.advancedResolve(ClsJavaCodeReferenceElementImpl.java:183)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:145)

{
   "pshopId":1,
   "pshopName":"肯德基",
   "logoUrl":"http://www.baidu.com/",
   "flavors":"湘菜, 米",
   "sales":1234,
   "groupons":12345,
   "evaluates":123,
   "averagePrice":12,
   "mobile":"13512345678",
   "city":"上海/普陀区",
   "address":"金沙江路1518弄",
   "license":1,
   "cooperationPlatforms":[
      {
         "platform":1,
         "url":"http://www.baidu.com/"
      }
   ],
   "createTime":"10-31 14:00:00",
   "potentialLevel":1,
   "claimStatus":1,
   "claimPerson":{
      "userName":"王小虎",
      "userEmail":"xiaohu.wang@ele.me",
      "mobile":"13512345678",
      "department":"上海张江战营"
   },
   "distance":"100米以内"
}

**Comment by zzz40500** [comment]
在1.5.0 上修复了
