### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by kovac777** [zzz40500/GsonFormat#80]
**plugin version 1.5**
**Android Studio version 2.3 RC1**

**Throw NPE when I formating this Json:**
`{
  "data": [
    {
      "id": "454104955b00401e9a570c956c2ac0a4",
      "subject": "Заголовок тикета",
      "last_ticket_comment_id": "decf9d2c3654464cb91304b679f800d1",
      "created_at": "2017-02-28T10:32:23+0300",
      "updated_at": "2017-02-28T10:32:59+0300",
      "team": {
        "id": "406e6c36020048079b0647c03d46cc6c",
        "name": "Nike",
        "created_at": "2016-11-30T22:41:33+0300",
        "updated_at": "2016-12-27T15:10:17+0300"
      },
      "user": {
        "id": 91,
        "name": "Max",
        "email": "kovac619@gmail.com",
        "photo_url": "https://by.assistent.cloud/storage/profiles/eeae16e0399eada4f7e1185c2f21efc8.png",
        "created_at": "2016-11-30T15:58:25+0300",
        "updated_at": "2017-02-28T08:14:58+0300"
      },
      "ticket_department": {
        "id": 1,
        "name": "Общий"
      }
    }
  ],
  "meta": {
    "pagination": {
      "total": 1,
      "count": 1,
      "per_page": 50,
      "current_page": 1,
      "total_pages": 1,
      "links": {}
    }
  }
}`

**Stacktrace:**
`java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:180)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:86)
	at org.gsonformat.intellij.action.DataWriter.execute(DataWriter.java:74)
	at org.gsonformat.intellij.action.DataWriter$1.run(DataWriter.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.gsonformat.intellij.action.DataWriter$2.onEndGenerateClass(DataWriter.java:101)
	at org.gsonformat.intellij.process.Processor.onEndGenerateClass(Processor.java:243)
	at org.gsonformat.intellij.process.Processor.generateClass(Processor.java:229)
	at org.gsonformat.intellij.process.Processor.generateClass(Processor.java:217)
	at org.gsonformat.intellij.process.Processor.generateClass(Processor.java:217)
	at org.gsonformat.intellij.process.Processor.process(Processor.java:51)
	at org.gsonformat.intellij.process.ClassProcessor.generate(ClassProcessor.java:24)
	at org.gsonformat.intellij.action.DataWriter.run(DataWriter.java:83)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:167)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:113)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:34)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:89)
	at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:168)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by kovac777** [comment]
in previous android studio version work perfectly

**Comment by illuzor** [comment]
I have the same issue, but in another case.
Steps to reproduce with [this json](https://gist.github.com/illuzor/75679944c09bac7a306341728682f665):
Insert it to GsonFormat window, click "ok" and [disable GenresBean](http://images.illuzor.com/uploads/gsonnull.png)

**Comment by kovac777** [comment]
I found solution - use previous version plugin!

**Comment by illuzor** [comment]
This is good, but why did you close the issue? It must be fixed in new version.
